### ISSUE TITLE
IsBusy は自動実装プロパティでなくただのプロパティですよね

### ISSUE THREAD

**Issue by amay077** [chomado/xamarin-dev-doc#13]
https://github.com/chomado/xamarin-dev-doc/blob/master/hands-on/readme.md#isbusy-プロパティ

> この SpeakersViewModel クラスの中に、bool値を get/set するための、バッキングフィールド(backing field)と 自動プロパティ(自動実装プロパティ/auto-properties)を作りましょう。

とありますが、バッキングフィールドを用意して、自力でset/getしているので、自動実装プロパティではないです。

本家の英文サイトも間違っているようですが。

**Comment by yoichinak** [comment]
https://github.com/xamarin/dev-days-labs/commit/73c8b36578daa071ba534a2643ad14e99076145d
本家masterでは修正されたようです。

**Comment by amay077** [comment]
↑プルリク出しました
