### ISSUE TITLE
SpeakerのIdの警告

### ISSUE THREAD

**Issue by yoichinak** [chomado/xamarin-dev-doc#15]
Speakerクラスに作成するよう指示されるプロパティの中にIdがありますが、これは継承元のAppServiceHelpers.Models.EntityDataに既にあり、警告が出ます。finishのコードには無いようなので、ドキュメント上でも削除してしまっていいかもしれません。

**Comment by ytabuchi** [comment]
最新の 1.0.4 の Helper ライブラリが UWP で動かないのと現在の Finish のコードも Helper ライブラリを使っていないので(Helper ライブラリを使って EntityTable を継承する場合はエラーが出ますが、使わない場合は id が必要っぽい)、id は消さずにドキュメントの方を直しました。(iOS／Androidは動作確認ずみ)

本 Issue はクローズで良いかと思います。

ありがとうございます！！！！

**Comment by yoichinak** [comment]
ありがとうございました:)
