### ISSUE TITLE
「以前のプレゼンテーション」とは

### ISSUE THREAD

**Issue by yoichinak** [chomado/xamarin-dev-doc#16]
「以前のプレゼンテーション」とは何でしょうか。
これでしょうか。
[Dev Days 3 - Azure Mobile Apps.pdf](https://github.com/xamarin/dev-days-labs/blob/2016/SlideDecks/Dev%20Days%203%20-%20Azure%20Mobile%20Apps.pdf)
このスライドはXamarin Dev Days Japanでも事前に紹介されるのでしょうか。

**Comment by ytabuchi** [comment]
こんにちは。私翻訳部分の箇所だと思いますが、そのスライドです。日本語に翻訳したものを使う可能性があり、その場合は公開するはずです。
